
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package menora.ccm.taxreport.services;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-10T11:40:41.668+03:00
 * Generated source version: 3.0.1
 * 
 */
public class TaxReportServiceClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://services.taxreport.ccm.menora/", "TaxReportServiceImplService");
        URL url = new URL("http://localhost:8080/TaxReportGenerator/services/taxreportservice?wsdl");
        // for tcp monitoring
        //URL url = new URL("http://localhost:8888/TaxReportGenerator/services/taxreportservice?wsdl");
               Service service = Service.create(url,serviceName);
        TaxReportService client = service.getPort(TaxReportService.class);
        TaxReportResponse resp = client.generateForId(2,1);
        System.out.println("got resp " + resp.getRetCode());
       
    }

}