/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.68 (1.7.4)
 * Generated at: 2017-08-30 10:27:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"he\" class=\"fullPage\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Sign In</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/jquery-1.11.2/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tjQuery.noConflict();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/webcomponentsjs/webcomponents.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/paper-input/paper-input.html\" />\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/paper-card/paper-card.html\" />\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/paper-button/paper-button.html\" />\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/paper-drawer-panel/paper-drawer-panel.html\" />\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/iron-flex-layout/iron-flex-layout.html\" />\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/iron-a11y-keys/iron-a11y-keys.html\" />\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/SoaArchiveClient/bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"import\" href=\"");
      out.print(request.getContextPath());
      out.write("/shared-styles.html\" />\r\n");
      out.write("\t<style is=\"custom-style\" include=\"shared-styles\"></style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"form\" class=\"flex-center-justified\" action=\"j_security_check\" method=\"post\">\r\n");
      out.write("\t\t<paper-card  image=\"");
      out.print(request.getContextPath());
      out.write("/images/menoraLogo.png\">\r\n");
      out.write("\t\t\t<div class=\"card-content\">\r\n");
      out.write("\t\t\t\t<paper-input label=\"User Name\" name=\"j_username\"></paper-input>\r\n");
      out.write("\t\t\t\t<paper-input label=\"Password\" name=\"j_password\" type=\"password\"></paper-input>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-actions\">\r\n");
      out.write("\t\t\t\t");

					String errorCode = request.getParameter("errorCode");
					if (errorCode != null) {
						if (errorCode.equals("invalidCredentials")) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<div>User or password are wrong/div>\r\n");
      out.write("\t\t\t\t");

					} else if (errorCode.equals("invalidLoginSession")) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<div>Login timeout - please re-login</div>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<paper-button class=\"loginButton\" raised>Login</paper-button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</paper-card>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar button = document.querySelector('paper-button');\r\n");
      out.write("\t\tbutton.addEventListener('tap', function() {\r\n");
      out.write("\t\t\tdocument.querySelector('form').submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
