/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'oded' at '10/5/16 10:05 AM' with Gradle 2.5
 *
 * @author oded, @date 10/5/16 10:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
