select count(* ) from INCOMING;
select count(* ) from OUTGOING;
select id, mqRfh2, incomingtime from INCOMING;
update incoming set mqRfh2='some value';

update incoming set servicename='bsrv' where id > 110 and id < 220;
update incoming set status='NEW';
update incoming set status='CLOSED_MANUALLY' where id <110;

alter table INCOMING add ( EXPIRYTIME  TIMESTAMP(9));
update incoming set EXPIRYTIME =TO_TIMESTAMP('2017-07-02 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF');

CREATE INDEX FROMOUTGOINGID_INX ON INCOMING (FROMOUTGOINGID);

create user soaarchive identified by soaarchive;
GRANT create session TO soaarchive;
GRANT create table TO soaarchive;
GRANT create view TO soaarchive;
GRANT create any trigger TO soaarchive;
GRANT create any procedure TO soaarchive;
GRANT create sequence TO soaarchive;
GRANT create synonym TO soaarchive;
GRANT all privileges TO soaarchive;
ALTER USER system IDENTIFIED BY system;
Exec DBMS_XDB.SETHTTPPORT(3010);


--<ScriptOptions statementTerminator=";"/>

ALTER TABLE QMGRCONNDATA DROP CONSTRAINT SYS_C007004;

DROP INDEX SYS_C007004;

DROP TABLE QMGRCONNDATA;

    

CREATE TABLE QMGRCONNDATA (
		ID NUMBER NOT NULL,
		CHLNAME VARCHAR2(255),
		IP VARCHAR2(255),
		PORT NUMBER,
		QMGRNAME VARCHAR2(255)
	);

CREATE UNIQUE INDEX SYS_C007004 ON QMGRCONNDATA (ID ASC);

ALTER TABLE QMGRCONNDATA ADD CONSTRAINT SYS_C007004 PRIMARY KEY (ID);
--<ScriptOptions statementTerminator=";"/>

ALTER TABLE PAYLOAD DROP CONSTRAINT SYS_C007002;

DROP INDEX SYS_C007002;

DROP TABLE PAYLOAD;

CREATE TABLE PAYLOAD (
		ID NUMBER NOT NULL,
		PAYLOAD VARCHAR2(255),
		PAYLOADSIZE NUMBER
	);

CREATE UNIQUE INDEX SYS_C007002 ON PAYLOAD (ID ASC);

ALTER TABLE PAYLOAD ADD CONSTRAINT SYS_C007002 PRIMARY KEY (ID);

--<ScriptOptions statementTerminator=";"/>

ALTER TABLE OPENJPA_SEQUENCE_TABLE DROP CONSTRAINT SYS_C007000;

DROP INDEX SYS_C007000;

DROP TABLE OPENJPA_SEQUENCE_TABLE;

CREATE TABLE OPENJPA_SEQUENCE_TABLE (
		ID NUMBER NOT NULL,
		SEQUENCE_VALUE NUMBER
	);

CREATE UNIQUE INDEX SYS_C007000 ON OPENJPA_SEQUENCE_TABLE (ID ASC);

ALTER TABLE OPENJPA_SEQUENCE_TABLE ADD CONSTRAINT SYS_C007000 PRIMARY KEY (ID);
--<ScriptOptions statementTerminator=";"/>

ALTER TABLE INCOMING DROP CONSTRAINT SYS_C007006;

DROP INDEX SYS_C007006;

DROP INDEX I_NCOMING_PAYLOAD;

DROP TABLE INCOMING;

--<ScriptOptions statementTerminator=";"/>

CREATE TABLE INCOMING (
		ID NUMBER NOT NULL,
		BIPMSG VARCHAR2(255),
		CLOSETIME TIMESTAMP(11),
		ERRORCODE VARCHAR2(255),
		ERRORMESSAGE VARCHAR2(255),
		ERRORTIME TIMESTAMP(11),
		FROMOUTGOINGID NUMBER,
		FROMQMGR VARCHAR2(255),
		FROMQUEUE VARCHAR2(255),
		FROMSERVERIP VARCHAR2(255),
		FROMSERVERNAME VARCHAR2(255),
		FULLEXCEPTION VARCHAR2(255),
		GETTIME TIMESTAMP(11),
		INCOMINGTIME TIMESTAMP(11),
		LASTUSER VARCHAR2(255),
		MQBACKOUTCOUNT NUMBER,
		MQID NUMBER,
		MQMESSAGEID NUMBER,
		MQRFH2 VARCHAR2(255),
		RERUNSNUM NUMBER,
		SERVICENAME VARCHAR2(255),
		SERVICETYPE VARCHAR2(255),
		STATUS VARCHAR2(255),
		STATUSTIME TIMESTAMP(11),
		PAYLOAD_ID NUMBER,
		EXPIRYTIME null
	);

CREATE INDEX I_NCOMING_PAYLOAD ON INCOMING (PAYLOAD_ID ASC);

CREATE INDEX FROMOUTGOINGID_INX ON INCOMING (FROMOUTGOINGID ASC);

CREATE UNIQUE INDEX SYS_C007006 ON INCOMING (ID ASC);

ALTER TABLE INCOMING ADD CONSTRAINT SYS_C007006 PRIMARY KEY (ID);


--<ScriptOptions statementTerminator=";"/>

ALTER TABLE OUTGOING DROP CONSTRAINT SYS_C007008;

DROP INDEX I_OUTGONG_PAYLOAD;

DROP INDEX SYS_C007008;

DROP TABLE OUTGOING;

CREATE TABLE OUTGOING (
		ID NUMBER NOT NULL,
		INCOMINGID NUMBER,
		MQID NUMBER,
		MQRFH2 VARCHAR2(255),
		RESENDTIME TIMESTAMP(11),
		TOQMGR VARCHAR2(255),
		TOQUEUE VARCHAR2(255),
		PAYLOAD_ID NUMBER
	);

CREATE INDEX I_OUTGONG_PAYLOAD ON OUTGOING (PAYLOAD_ID ASC);

CREATE UNIQUE INDEX SYS_C007008 ON OUTGOING (ID ASC);

ALTER TABLE OUTGOING ADD CONSTRAINT SYS_C007008 PRIMARY KEY (ID);




